# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Team 3128: Aluminium Narwhals"
email: info@team3128.org
description: "Copyright Â© 2015-2020 Team 3128: Aluminum Narwhals"
baseurl: ""
url: "http://team3128.org"
github_username: Team3128
excerpt_separator: ?more?

# Build settings
markdown: kramdown

# Gem Plugins
plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Google Analytics
google_analytics: UA-179140189-1
